import = [
    "~/.config/alacritty/themes/themes/blood_moon.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
dimensions.columns = 200
dimensions.lines = 60

padding.x = 10
padding.y = 10

position.x = 350
position.y = 350

decorations = "Buttonless"

opacity = 0.85
blur = true

option_as_alt = "Both"

[scrolling]
history = 100000
multiplier = 10

[cursor]
style.shape = "Beam"
style.blinking = "Never"

[font]
normal.family = "Hack Nerd Font Mono"

size = 14
